import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';

import {
  GoogleAuthProvider,
  onAuthStateChanged,
  signInWithPopup,
  signOut,
  User,
} from 'firebase/auth';

import { auth } from '../lib/firebase';
import Products from '../components/Products';
import Purchases from '../components/purchases';

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      setUser(user);
    });
  }, []);

  const login = () => {
    signInWithPopup(auth, new GoogleAuthProvider());
  };

  const logout = () => {
    signOut(auth);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user ? (
          <button
            onClick={logout}
            className="bg-transparent hover:to-blue-500 text-blue-800 font-semibold hover:text-white hover:bg-blue-600 p-1 my-1 border border-blue-400 hover:border-transparent rounded-xl"
          >
            Logout
          </button>
        ) : (
          <button
            onClick={login}
            className="bg-transparent hover:to-blue-500 text-blue-800 font-semibold hover:text-white hover:bg-blue-600 p-1 my-1 border border-blue-400 hover:border-transparent rounded-xl"
          >
            Login
          </button>
        )}
        {user && <p>ようこそ {user.displayName}さん</p>}
        {user && <Products user={user} />}
        {user && <Purchases user={user} />}
      </main>
    </div>
  );
};

export default Home;
